name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.2+1
  sqlite3: ^1.5.1
  path: ^1.9.1
  analyzer: ^6.2.0
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
